Controllers/BibliotekaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Osvita.Controllers
{
    public class BibliotekaController : Controller
    {
        // GET: Biblioteka
        public ActionResult Main()
        {
            return View();
        }
    }
}

Controllers/SportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Osvita.Controllers
{
    public class SportController : Controller
    {
        // GET: Sport
        public ActionResult Main()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - RadVOK</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/cssowl")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Головна", "Index", "Home")</li>
                    <li>@Html.ActionLink("Про нас", "About", "Home")</li>
                    <li>@Html.ActionLink("Контакти", "Contact", "Home")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Розділи<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Освіта", "Index", "Home")</li>
                            <li class="dropdown-submenu">
                                <a class="test" tabindex="-1" href="#">Культура   <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Бібліотека", "Main", "Biblioteka")</li>
                                    <li><a tabindex="-1" href="#">Музей </a></li>
                                    <li class="dropdown-submenu">
                                        <a class="test" href="#">Клуби <span class="caret"></span></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="#">Клуб 1</a></li>
                                            <li><a href="#">Клуб 2</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li>@Html.ActionLink("Молодь", "Main", "Biblioteka")</li>
                            <li>@Html.ActionLink("Спорт", "Main", "Sport")</li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.Partial("_LoginPartial")</li>
                </ul>
            </div>
        </div>
    </nav>
    @*<div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Головна", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Про нас", "About", "Home")</li>
                    <li>@html.actionlink("контакти", "contact", "home")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Розділи <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                            <li class="divider"></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>*@
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    <div class="container">
        <footer>
            <p>&copy; @DateTime.Now.Year - radvok.org.ua</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/owl")
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        $(document).ready(function () {
            $('.owl-carousel').owlCarousel({
                loop: true,
                margin: 10,
                responsiveClass: true,
                responsive: {
                    0: {
                        items: 1,
                        nav: true
                    },
                    600: {
                        items: 3,
                        nav: false
                    },
                    800: {
                        items: 4,
                        nav: true
                    },
                    1000: {
                        items: 5,
                        nav: true,
                        loop: false
                    },
                    1400: {
                        items: 6,
                        nav: true,
                        loop: false
                    }
                }
            });
        });
    </script>
    <script>
        $(document).ready(function () {
            $('.dropdown-submenu a.test').on("click", function (e) {
                $(this).next('ul').toggle();
                e.stopPropagation();
                e.preventDefault();
            });
        });
    </script>
</body>
</html>